/**
 * scenarios.js — All 10 emergency scenario definitions
 */

export const SCENARIOS = [
  {
    id: 'oxygen_leak',
    title: 'OXYGEN LEAK RESPONSE',
    tag: 'MISSION ALPHA-1',
    icon: '💨',
    difficulty: 'critical',
    duration: 8,
    maxScore: 1000,
    description: 'A micro-fracture has been detected in the primary oxygen storage system. The leak is causing rapid pressure loss in the crew module.',
    situation: 'Sensors have detected a 0.8 kPa/min pressure drop in the forward cabin. Oxygen reserves are falling. You must locate and seal the breach before cabin oxygen becomes critical.',
    objectives: [
      'Read the pressure telemetry and confirm the anomaly',
      'Locate the oxygen leak in the spacecraft',
      'Retrieve the emergency repair kit',
      'Seal the hull rupture with a patch',
      'Restore cabin oxygen using the reserve tanks',
      'Verify pressure stabilization',
    ],
    color: '#0EA5E9',
    envType: 'interior',
    leakLocations: ['Port wall panel A3', 'Overhead oxygen duct', 'Airlock seal gasket'],
    items: ['Patch Kit', 'Oxygen Mask', 'O₂ Tank'],
    sounds: ['pressure_alarm', 'hiss'],
    telemetryChanges: {
      o2: -2, pressure: -3, hull: 0, co2: 0.5,
    },
    quiz: [
      {
        q: 'What is the FIRST action when detecting cabin pressure loss?',
        options: ['Don oxygen mask', 'Call mission control', 'Look for the leak', 'Seal the airlock'],
        correct: 0,
        explanation: 'Personal safety first. An oxygen mask ensures you remain conscious while investigating.',
      },
      {
        q: 'Which instrument indicates oxygen system pressure?',
        options: ['Altimeter', 'O₂ Partial Pressure Gauge', 'CO₂ Scrubber', 'Battery Monitor'],
        correct: 1,
        explanation: 'The O₂ Partial Pressure Gauge shows current oxygen levels in the cabin atmosphere.',
      },
      {
        q: 'A cabin pressure of below what kPa is considered life-threatening?',
        options: ['80 kPa', '70 kPa', '60 kPa', '50 kPa'],
        correct: 1,
        explanation: 'Below 70 kPa, oxygen partial pressure becomes too low to sustain consciousness.',
      },
      {
        q: 'What material is used to seal micro-fractures in a spacecraft hull?',
        options: ['Duct tape', 'Epoxy sealant patch', 'Welding', 'Rubber gasket'],
        correct: 1,
        explanation: 'Space-grade epoxy sealant patches are designed for rapid deployment in emergencies.',
      },
      {
        q: 'After sealing a leak, what must be done next?',
        options: ['Report to mission control', 'Equalize cabin pressure', 'Sleep', 'Check food supplies'],
        correct: 1,
        explanation: 'Pressure equalization restores proper atmospheric balance for the crew.',
      },
    ],
  },
  {
    id: 'spacecraft_fire',
    title: 'SPACECRAFT FIRE SUPPRESSION',
    tag: 'MISSION BETA-2',
    icon: '🔥',
    difficulty: 'critical',
    duration: 6,
    maxScore: 1200,
    description: 'A short circuit in the laboratory module has ignited insulation material. Smoke is spreading through the ventilation system.',
    situation: 'Smoke detectors triggered in Lab Module 3. CO₂ levels rising. The fire must be controlled before it reaches electrical panels or oxygen lines.',
    objectives: [
      'Identify the fire source from sensor data',
      'Shut down ventilation to stop smoke spread',
      'Don oxygen mask before approaching fire',
      'Use CO₂ fire extinguisher on the fire',
      'Inspect and seal damaged panels',
      'Restart ventilation and monitor air quality',
    ],
    color: '#EF4444',
    envType: 'interior',
    leakLocations: ['Lab Module 3 east wall', 'Electrical Panel B', 'Behind Rack 7'],
    items: ['Extinguisher', 'Oxygen Mask', 'Repair Panel'],
    sounds: ['fire_alarm', 'crackle'],
    telemetryChanges: {
      o2: -1, co2: 2, temp: 8, battery: -5,
    },
    quiz: [
      {
        q: 'Why should ventilation be shut off during a spacecraft fire?',
        options: ['To save power', 'To prevent spreading smoke and fire', 'Standard procedure', 'To cool the fire'],
        correct: 1,
        explanation: 'Ventilation spreads smoke and oxygen to the fire, causing rapid expansion.',
      },
      {
        q: 'Which extinguisher type is safe to use in a spacecraft cabin?',
        options: ['Water', 'CO₂', 'Foam', 'Sand'],
        correct: 1,
        explanation: 'CO₂ extinguishers are used in spacecraft as they leave no residue and do not damage electronics.',
      },
      {
        q: 'Before fighting a fire in space, what must you do first?',
        options: ['Get a partner', 'Don oxygen mask', 'Photograph the fire', 'Call ground control'],
        correct: 1,
        explanation: 'Smoke can incapacitate crew within minutes. Oxygen mask is mandatory before engagement.',
      },
      {
        q: 'Fires in spacecraft burn differently because:',
        options: ['Less fuel', 'No gravity affects flame behavior', 'Higher pressure', 'More oxygen'],
        correct: 1,
        explanation: 'In microgravity, flames form spherical shapes and burn at lower temperatures without convection.',
      },
      {
        q: 'After extinguishing the fire, what is the next critical step?',
        options: ['Resume normal operations', 'Monitor air quality for toxins', 'Eat a meal', 'Exercise'],
        correct: 1,
        explanation: 'Smoke contains toxic particles. Air quality must be verified before removing oxygen masks.',
      },
    ],
  },
  {
    id: 'equipment_failure',
    title: 'CRITICAL EQUIPMENT FAILURE',
    tag: 'MISSION GAMMA-3',
    icon: '⚙️',
    difficulty: 'medium',
    duration: 10,
    maxScore: 900,
    description: 'The life support computer has crashed. Multiple subsystems are offline. Manual intervention required to restore functionality.',
    situation: 'ECLSS (Environmental Control and Life Support System) has experienced a software fault. Power relay failed. Manual reboot sequence and component replacement needed.',
    objectives: [
      'Diagnose the failed subsystem via manual telemetry',
      'Retrieve replacement circuit board from equipment locker',
      'Disconnect main power before working on electronics',
      'Replace the faulty relay in Panel C-4',
      'Reconnect power and initiate ECLSS reboot sequence',
      'Verify all life support systems are nominal',
    ],
    color: '#10B981',
    envType: 'interior',
    leakLocations: ['Panel C-4', 'Life Support Computer Bay', 'Power Relay Junction'],
    items: ['Repair Kit', 'Circuit Board', 'Multi-tool'],
    sounds: ['electrical_buzz', 'reboot'],
    telemetryChanges: {
      battery: -20, o2: -0.5, co2: 0.3,
    },
    quiz: [
      {
        q: 'What does ECLSS stand for?',
        options: ['Emergency Control Life Support System', 'Environmental Control and Life Support System', 'Electronic Control Launch Safety System', 'External Cabin Life Support System'],
        correct: 1,
        explanation: 'ECLSS manages atmosphere, water, and other life support functions on the ISS and spacecraft.',
      },
      {
        q: 'Before replacing electronics on a spacecraft, you must:',
        options: ['Back up data', 'Disconnect power first', 'Wear gloves', 'Inform crew'],
        correct: 1,
        explanation: 'Disconnecting power prevents electrocution and accidental short circuits during repair.',
      },
      {
        q: 'A software fault causing system failure is called:',
        options: ['Hardware error', 'BSOD', 'Software anomaly', 'Critical fault exception'],
        correct: 2,
        explanation: 'In aerospace engineering, unexpected software behavior is classified as a software anomaly.',
      },
      {
        q: 'Power rerouting in a spacecraft means:',
        options: ['Disconnecting solar panels', 'Directing power through alternate circuits', 'Increasing battery output', 'Reducing consumption'],
        correct: 1,
        explanation: 'Alternate power routing maintains critical systems when primary circuits fail.',
      },
      {
        q: 'The crew should document all repairs because:',
        options: ['Standard protocol only', 'For insurance purposes', 'Mission control needs records for future flights', 'NASA regulations'],
        correct: 2,
        explanation: 'All repairs are documented to improve procedures and ensure mission engineers can analyze the failure.',
      },
    ],
  },
  {
    id: 'eva_emergency',
    title: 'EVA EMERGENCY',
    tag: 'MISSION DELTA-4',
    icon: '🧑‍🚀',
    difficulty: 'critical',
    duration: 12,
    maxScore: 1500,
    description: 'During an extravehicular activity, your safety tether has failed. You are drifting away from the station.',
    situation: 'Tether lock mechanism failure detected. You are in open space 50m from the station. Suit oxygen remaining: 28 minutes. SAFER jetpack is available.',
    objectives: [
      'Activate SAFER (Simplified Aid For EVA Rescue) jetpack',
      'Stabilize rotation using attitude thrusters',
      'Navigate back to the nearest airlock',
      'Reconnect safety tether to the station handhold',
      'Verify suit integrity and oxygen levels',
      'Enter airlock and begin re-pressurization',
    ],
    color: '#8B5CF6',
    envType: 'exterior',
    leakLocations: [],
    items: ['SAFER Jetpack', 'Tether', 'Oxygen Tank'],
    sounds: ['suit_alarm', 'thruster'],
    telemetryChanges: {
      suit: -5, o2: -3, hr: 20,
    },
    quiz: [
      {
        q: 'What does SAFER stand for?',
        options: [
          'Simplified Aid For EVA Rescue',
          'Space Astronaut Free Escape Rig',
          'Secondary Astronaut Flight Equipment Rig',
          'Simplified Attitude Flight Escape Relay',
        ],
        correct: 0,
        explanation: 'SAFER is a small, self-contained propulsion system worn like a backpack during EVA.',
      },
      {
        q: 'During a tether failure, the FIRST action is:',
        options: ['Panic and call for help', 'Activate SAFER and stabilize', 'Wait for rescue', 'Remove suit'],
        correct: 1,
        explanation: 'Stabilizing prevents uncontrolled tumbling, which wastes oxygen and fuel.',
      },
      {
        q: 'Normal EVA suit oxygen supply provides approximately:',
        options: ['2 hours', '8 hours', '30 minutes', '5 hours'],
        correct: 1,
        explanation: 'Standard NASA EVA suits provide up to 8 hours of consumables for planned operations.',
      },
      {
        q: 'The primary danger of uncontrolled EVA tumbling is:',
        options: ['Motion sickness', 'Rapid oxygen depletion and disorientation', 'Radio loss', 'Suit puncture'],
        correct: 1,
        explanation: 'Physical exertion and anxiety cause accelerated breathing, rapidly depleting suit oxygen.',
      },
      {
        q: 'After returning to the airlock, airlock re-pressurization takes approximately:',
        options: ['5 seconds', '5 minutes', '30 seconds', '1 hour'],
        correct: 1,
        explanation: 'Airlock pressurization takes approximately 3-5 minutes to ensure complete atmospheric integrity.',
      },
    ],
  },
  {
    id: 'debris_strike',
    title: 'ORBITAL DEBRIS STRIKE',
    tag: 'MISSION EPSILON-5',
    icon: '☄️',
    difficulty: 'high',
    duration: 10,
    maxScore: 1300,
    description: 'A fragment of orbital debris has struck the spacecraft hull, creating a micro-breach and damaging the solar panel array.',
    situation: 'Impact detected on port hull section. Micro-breach detected. Solar panel junction damaged. Hull integrity at 72%. Immediate response required.',
    objectives: [
      'Assess hull breach location via sensor sweep',
      'Seal interior side of breach with temporary patch',
      'Perform EVA to inspect exterior damage',
      'Replace damaged solar panel junction cable',
      'Restore hull structural integrity',
      'Resume nominal orbit and power generation',
    ],
    color: '#F59E0B',
    envType: 'both',
    leakLocations: ['Port hull section P-7', 'Solar panel array junction', 'External sensor array'],
    items: ['Patch Kit', 'EVA Suit', 'Replacement Cable'],
    sounds: ['impact', 'hull_alarm'],
    telemetryChanges: {
      hull: -28, battery: -15, pressure: -2,
    },
    quiz: [
      {
        q: 'Orbital debris travels at approximately:',
        options: ['100 km/h', '1,000 km/h', '28,000 km/h', '300,000 km/h'],
        correct: 2,
        explanation: 'Objects in LEO travel at ~28,000 km/h. Even tiny fragments carry enormous kinetic energy.',
      },
      {
        q: 'What is the first sensor to detect a hull breach?',
        options: ['Temperature sensor', 'Pressure differential sensor', 'Oxygen sensor', 'Motion sensor'],
        correct: 1,
        explanation: 'Pressure differential sensors immediately detect changes in hull integrity.',
      },
      {
        q: 'A "micro-breach" is typically smaller than:',
        options: ['1mm', '1cm', '5cm', '10cm'],
        correct: 1,
        explanation: 'Micro-breaches under 1cm can be sealed with onboard emergency patch kits.',
      },
      {
        q: 'Who is responsible for tracking orbital debris?',
        options: ['NASA only', 'US Space Surveillance Network and ESA', 'SpaceX', 'Local observatories'],
        correct: 1,
        explanation: 'The US SSN and ESA track thousands of debris objects and provide collision warnings.',
      },
      {
        q: 'After a debris impact, crews should:',
        options: ['Continue normal operations', 'Document damage, assess systems, report to mission control', 'Abandon ship', 'Repair immediately without assessment'],
        correct: 1,
        explanation: 'Systematic assessment before action prevents hasty decisions that could worsen the situation.',
      },
    ],
  },
  {
    id: 'pressure_loss',
    title: 'CABIN PRESSURE LOSS',
    tag: 'MISSION ZETA-6',
    icon: '📉',
    difficulty: 'critical',
    duration: 7,
    maxScore: 1100,
    description: 'Catastrophic pressure drop detected in the habitation module. All crew must take immediate emergency action.',
    situation: 'Pressure loss rate: 5 kPa/min. Module may become uninhabitable in under 2 minutes. Emergency suit protocols must be activated.',
    objectives: [
      'Recognize the critical pressure alarm',
      'Don emergency pressure suit immediately',
      'Isolate the habitation module by closing module hatches',
      'Locate the major pressure loss source',
      'Apply emergency seal to the breach',
      'Re-pressurize the module from reserves',
    ],
    color: '#EF4444',
    envType: 'interior',
    leakLocations: ['Hatch seal ring', 'Observation window frame', 'External equipment port'],
    items: ['Pressure Suit', 'Emergency Patch', 'O₂ Reserve'],
    sounds: ['pressure_alarm', 'decompression'],
    telemetryChanges: {
      pressure: -8, o2: -3, hr: 35,
    },
    quiz: [
      {
        q: 'Rapid decompression from sea level to 0.5 atm causes:',
        options: ['Mild discomfort', 'Unconsciousness in 10-15 seconds', 'No effect', 'Nausea only'],
        correct: 1,
        explanation: 'At 0.5 atm, oxygen partial pressure is insufficient. Time of useful consciousness is ~10-15 seconds.',
      },
      {
        q: 'The donning time goal for an emergency pressure suit is:',
        options: ['30 minutes', '5 minutes', '10 seconds', 'Under 2 minutes'],
        correct: 3,
        explanation: 'Astronauts train extensively to don emergency suits in under 2 minutes.',
      },
      {
        q: 'Why isolate a depressurizing module with hatches?',
        options: ['Privacy', 'Prevent cascade failure to other modules', 'Temperature control', 'Standard procedure'],
        correct: 1,
        explanation: 'Hatch isolation preserves air in other modules and limits the area affected.',
      },
      {
        q: 'The "Time of Useful Consciousness" (TUC) at 30,000 feet altitude equivalent is:',
        options: ['1 hour', '30 minutes', '1-2 minutes', '5 minutes'],
        correct: 2,
        explanation: 'TUC drops dramatically with altitude. Above 40,000ft equivalent, TUC is under 15 seconds.',
      },
      {
        q: 'What backup system repressurizes a spacecraft module?',
        options: ['External pump', 'High-pressure gas reserves', 'Chemical oxygen generators', 'Solar panels'],
        correct: 1,
        explanation: 'High-pressure nitrogen/oxygen reserves can repressurize modules after emergency repairs.',
      },
    ],
  },
  {
    id: 'electrical_failure',
    title: 'ELECTRICAL FAILURE',
    tag: 'MISSION ETA-7',
    icon: '⚡',
    difficulty: 'medium',
    duration: 9,
    maxScore: 850,
    description: 'A power distribution failure has knocked out 40% of spacecraft systems. Emergency power conservation protocols required.',
    situation: 'Primary power bus failure. Battery reserves at 34% and falling. Non-essential systems must be powered down. Critical systems must be maintained.',
    objectives: [
      'Identify failed power bus from panel indicators',
      'Switch to emergency battery power',
      'Power down non-essential systems manually',
      'Repair the primary power distribution fuse',
      'Restore power to critical life support systems',
      'Verify solar panels are charging correctly',
    ],
    color: '#F59E0B',
    envType: 'interior',
    leakLocations: ['Main power panel', 'Battery bay', 'Solar array controller'],
    items: ['Fuse Kit', 'Multi-meter', 'Power Tool'],
    sounds: ['electrical_buzz', 'power_down'],
    telemetryChanges: {
      battery: -40, temp: -3,
    },
    quiz: [
      {
        q: 'During a power emergency, which systems get priority power?',
        options: ['Entertainment systems', 'Life support and communication', 'Science experiments', 'Crew quarters'],
        correct: 1,
        explanation: 'Life support (O₂, CO₂ removal, temperature) and communication are always highest priority.',
      },
      {
        q: 'The ISS primary power source is:',
        options: ['Nuclear reactor', 'Fuel cells', 'Solar arrays', 'Battery packs'],
        correct: 2,
        explanation: 'The ISS uses eight 73m solar arrays generating ~84-120 kW of electricity.',
      },
      {
        q: 'A blown fuse in spacecraft electronics indicates:',
        options: ['Normal wear', 'Short circuit or overload condition', 'Software error', 'Temperature extreme'],
        correct: 1,
        explanation: 'Fuses protect circuits from overcurrent caused by shorts or overloads.',
      },
      {
        q: 'Spacecraft use which type of electrical system primarily?',
        options: ['120V AC', '28V DC', '240V AC', '12V DC'],
        correct: 1,
        explanation: 'Most spacecraft use 28V DC for compatibility with avionics and to minimize wiring weight.',
      },
      {
        q: 'After electrical repairs, what must be checked first?',
        options: ['Computer programs', 'Current and voltage stability', 'Crew comfort', 'Food supplies'],
        correct: 1,
        explanation: 'Electrical stability must be confirmed before reconnecting systems to prevent cascade failure.',
      },
    ],
  },
  {
    id: 'solar_damage',
    title: 'SOLAR PANEL DAMAGE',
    tag: 'MISSION THETA-8',
    icon: '🔆',
    difficulty: 'medium',
    duration: 11,
    maxScore: 900,
    description: 'Solar panels 3A and 3B are offline after micrometeorite damage. Power generation capacity reduced by 30%.',
    situation: 'Solar tracking system reports panels 3A/3B failed. Power deficit detected. EVA required to inspect and repair junction boxes.',
    objectives: [
      'Diagnose solar panel array failure via telemetry',
      'Calculate power budget and disable non-essentials',
      'Suit up and perform EVA inspection',
      'Replace damaged solar cell junction connectors',
      'Verify panel articulation and sun tracking',
      'Confirm power generation restored to nominal',
    ],
    color: '#F59E0B',
    envType: 'exterior',
    leakLocations: ['Solar panel 3A', 'Solar panel 3B', 'Array junction box C'],
    items: ['EVA Suit', 'Replacement Connector', 'Tether'],
    sounds: ['static', 'clicking'],
    telemetryChanges: {
      battery: -30,
    },
    quiz: [
      {
        q: 'ISS solar panels track the sun using:',
        options: ['Crew manual rotation', 'Alpha Joint Gimbal Assembly', 'Fixed position', 'Magnetic alignment'],
        correct: 1,
        explanation: 'The Alpha and Beta Gimbal Assemblies rotate the solar array to track the sun.',
      },
      {
        q: 'Solar cell efficiency in space is affected most by:',
        options: ['Time of day', 'Radiation degradation over time', 'Temperature only', 'Panel color'],
        correct: 1,
        explanation: 'Cosmic radiation gradually degrades solar cell efficiency over years in orbit.',
      },
      {
        q: 'During an EVA solar panel repair, the greatest risk is:',
        options: ['Sunburn', 'Electrocution from panel voltage', 'Drifting too far', 'Getting too cold'],
        correct: 1,
        explanation: 'Solar panels generate up to 100V which can be lethal. Proper isolation is essential.',
      },
      {
        q: 'When a solar panel is damaged, what increases in load?',
        options: ['Propulsion system', 'Battery drain on remaining panels', 'Solar panel output', 'Nothing changes'],
        correct: 1,
        explanation: 'Remaining panels and batteries must supply additional load, accelerating battery discharge.',
      },
      {
        q: 'Power budget management means:',
        options: ['Spending less money', 'Balancing available power with consumption requirements', 'Reducing crew count', 'Turning off all systems'],
        correct: 1,
        explanation: 'Power budget management ensures critical systems operate within available generation capacity.',
      },
    ],
  },
  {
    id: 'navigation_failure',
    title: 'NAVIGATION FAILURE',
    tag: 'MISSION IOTA-9',
    icon: '🧭',
    difficulty: 'low',
    duration: 8,
    maxScore: 750,
    description: 'The inertial navigation system (INS) has lost alignment. GPS signals are intermittent. Manual star navigation required.',
    situation: 'Primary GPS module offline. INS drift detected. Backup navigation must be initialized using star tracker and manual calculations.',
    objectives: [
      'Confirm primary navigation system failure',
      'Initialize backup star tracker system',
      'Calibrate navigation using three reference stars',
      'Calculate current orbital position manually',
      'Enter corrected trajectory data',
      'Confirm alignment with ground station',
    ],
    color: '#10B981',
    envType: 'interior',
    leakLocations: [],
    items: ['Star Chart', 'Navigation Computer', 'Calculator'],
    sounds: ['beeping', 'radio'],
    telemetryChanges: {},
    quiz: [
      {
        q: 'What is an Inertial Navigation System (INS)?',
        options: [
          'GPS system',
          'A system that calculates position from motion without external references',
          'Radio navigation',
          'Star tracker',
        ],
        correct: 1,
        explanation: 'INS uses accelerometers and gyroscopes to calculate position from initial known state.',
      },
      {
        q: 'Star navigation uses a minimum of how many stars for a position fix?',
        options: ['1', '2', '3', '10'],
        correct: 2,
        explanation: 'Three star sightings provide the celestial triangle needed for an accurate 3D position fix.',
      },
      {
        q: 'GPS satellite signals are useless in deep space because:',
        options: ['No internet', 'Signals too weak at large distances', 'Wrong frequency', 'Weather interference'],
        correct: 1,
        explanation: 'GPS satellites orbit Earth. Their signals are too weak and mis-pointed for deep space missions.',
      },
      {
        q: 'Spacecraft orbital position is described by:',
        options: ['Latitude/Longitude', 'Six Keplerian elements', 'GPS coordinates', 'Star maps'],
        correct: 1,
        explanation: 'The six Keplerian elements (e.g., inclination, eccentricity) fully describe an orbit.',
      },
      {
        q: 'Mission Control can help with navigation by:',
        options: ['Sending crew directions', 'Providing TDRS relay and tracking data', 'Using telescopes', 'Radio beacons'],
        correct: 1,
        explanation: 'NASA uses the Tracking and Data Relay Satellite system to provide navigation fixes.',
      },
    ],
  },
  {
    id: 'comm_blackout',
    title: 'COMMUNICATION BLACKOUT',
    tag: 'MISSION KAPPA-10',
    icon: '📡',
    difficulty: 'low',
    duration: 7,
    maxScore: 700,
    description: 'All communication with Mission Control has been lost. The antenna array has failed. The crew must restore contact autonomously.',
    situation: 'No communication for 47 minutes. Antenna gimbal failure suspected. Backup radio deployment required. Follow emergency communication protocol.',
    objectives: [
      'Diagnose communication system failure',
      'Switch to backup UHF emergency radio',
      'Deploy secondary antenna from equipment locker',
      'Align antenna using manual star sighting',
      'Transmit emergency beacon on recovery frequency',
      'Confirm contact with Mission Control',
    ],
    color: '#10B981',
    envType: 'interior',
    leakLocations: [],
    items: ['Backup Radio', 'Antenna', 'Signal Analyzer'],
    sounds: ['static', 'beeping'],
    telemetryChanges: {},
    quiz: [
      {
        q: 'How long can a spacecraft crew operate independently during communication blackout?',
        options: ['Minutes only', 'Hours to days using pre-planned procedures', 'Not at all', 'Indefinitely'],
        correct: 1,
        explanation: 'Astronauts are trained in autonomous procedures to handle emergencies during comms loss.',
      },
      {
        q: 'The ISS has communication blackouts when:',
        options: ['Crew is sleeping', 'Orbiting on the far side of Earth from relay satellites', 'It is night', 'During docking'],
        correct: 1,
        explanation: 'Orbital mechanics cause brief communication gaps, mitigated by TDRS relay satellites.',
      },
      {
        q: 'An emergency beacon frequency used by spacecraft is:',
        options: ['FM radio band', '406 MHz international distress frequency', 'WiFi frequency', 'Bluetooth'],
        correct: 1,
        explanation: '406 MHz is the internationally designated distress frequency for COSPAS-SARSAT beacons.',
      },
      {
        q: 'UHF radio in space is primarily used for:',
        options: ['Internet', 'Short-range EVA communication', 'Ground tracking', 'Science data'],
        correct: 1,
        explanation: 'UHF is the primary voice link for EVA crew to the station and ground.',
      },
      {
        q: 'Manually aligning an antenna requires knowing:',
        options: ['Wind direction', 'Spacecraft attitude and target station position', 'Temperature', 'Time only'],
        correct: 1,
        explanation: 'Accurate antenna pointing requires precise knowledge of spacecraft orientation and ground station orbital position.',
      },
    ],
  },
];

export function getScenario(id) {
  return SCENARIOS.find(s => s.id === id) || SCENARIOS[0];
}

export default SCENARIOS;
